### ISSUE TITLE
Fails to build android - resource android:attr/lStar not found

### ISSUE THREAD

**Issue by upngo** [marconett/react-native-sha1#2]
Upgraded from react native 0.69 -> 70.1 and the app no longer builds.
This appears to be an issue for many older plugins.
A simple google search for this appear lots.

**Comment by upngo** [comment]
`> Task :react-native-sha1:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-sha1:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/tom/work/mobile-app/Builderscrack/node_modules/react-native-sha1/android/build/intermediates/merged_res/release/values/values.xml:2717: AAPT: error: resource android:attr/lStar not found.
`

**Comment by upngo** [comment]
`> Task :react-native-sha1:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-sha1:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/............../node_modules/react-native-sha1/android/build/intermediates/merged_res/release/values/values.xml:2717: AAPT: error: resource android:attr/lStar not found.
`

**Comment by upngo** [comment]
the main library you've forked provided sha1 now anyway....not clear from documentation though.

`import { sha1 } from 'react-native-sha256';
`

https://github.com/itinance/react-native-sha256

**Comment by danielsvec** [comment]
I had the same problem on RN 0.71.5.
Solved it with react-native-sha256, thank you @upngo.

**Comment by marconett** [comment]
I am sorry, I must have missed this issue last year :(

This lib is now deprecated as react-native-sha256 supports sha1.
I still updated it to support newer android versions, but new users should use react-native-sha256.
